package cn.listenerhe.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePoems<M extends BasePoems<M>> extends Model<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setTitle(String title) {
		set("title", title);
		return (M)this;
	}

	public String getTitle() {
		return getStr("title");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setAuthorId(Long authorId) {
		set("author_id", authorId);
		return (M)this;
	}

	public Long getAuthorId() {
		return getLong("author_id");
	}

	public M setDynasty(String dynasty) {
		set("dynasty", dynasty);
		return (M)this;
	}

	public String getDynasty() {
		return getStr("dynasty");
	}

	public M setAuthor(String author) {
		set("author", author);
		return (M)this;
	}

	public String getAuthor() {
		return getStr("author");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("update_date", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("update_date");
	}

}
