package cn.listenerhe.model;


import cn.listenerhe.model.base.BasePoems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Poems extends BasePoems<Poems> {
	public static final Poems dao = new Poems().dao();


}
